version: "3.8"
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://nikacv97:Munchen1860@ac-nvdc21t-shard-00-00.6zajxen.mongodb.net:27017,ac-nvdc21t-shard-00-01.6zajxen.mongodb.net:27017,ac-nvdc21t-shard-00-02.6zajxen.mongodb.net:27017/footballStats?ssl=true&replicaSet=atlas-11o6bu-shard-0&authSource=admin&appName=football-stats-cluster
      - NODE_ENV=production
      - PORT=5000

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

